"""initial

Revision ID: d90bad72eed4
Revises: 
Create Date: 2026-02-20 10:32:18.263467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd90bad72eed4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('serial_number',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_asset_asset_tag'))
        batch_op.drop_constraint(batch_op.f('asset_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('updated_at')
        batch_op.drop_column('warranty_until')
        batch_op.drop_column('owner_id')
        batch_op.drop_column('notes')
        batch_op.drop_column('purchase_date')
        batch_op.drop_column('asset_tag')
        batch_op.drop_column('assigned_to')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_user_token'))
        batch_op.drop_column('token')
        batch_op.drop_column('last_seen')
        batch_op.drop_column('token_expiration')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', mysql.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('token_expiration', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('last_seen', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('token', mysql.VARCHAR(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_token'), ['token'], unique=True)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('role')

    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', mysql.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('asset_tag', mysql.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('purchase_date', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('notes', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('owner_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('warranty_until', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('asset_ibfk_1'), 'user', ['owner_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_asset_asset_tag'), ['asset_tag'], unique=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('serial_number',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
